# Step 3 — Semantic comparison

This notebook has two phases:

1. **Classification** — runs `LLMFileClassifier` (Java, via the Gradle `classifyLLMFiles` task) over every `.crml` file in `generated/` and writes `generated/results.csv` with one of `SYNTAX | COMPILATION | LOAD | CORRECT`.
2. **Semantic testing** — for every `CORRECT` model whose domain is in the harness registry, runs `FuzzHarness` (differential simulation) against the reference implementation and records pass/fail counts.

The two result sets are merged into `generated/results_semantic.csv`.

**Prerequisites:** a running Modelica installation (`omc` on PATH) and the Gradle wrapper at repo root.

## 1  Classify generated CRML files

Runs `crml.experiments.LLMFileClassifier` via the pre-configured Gradle task `experiments:classifyLLMFiles`. The task:
- parses each `.crml` (syntax check)
- compiles CRML → Modelica
- loads the generated `.mo` with `omc`

The result is written to `generated/results.csv`.

In [1]:
from pathlib import Path
import subprocess

ROOT          = Path(".").resolve().parent   # CRML repo root
GENERATED_DIR = Path("generated")            # relative to notebook CWD (LLM/)

gradlew = str(ROOT / "gradlew")

print("Running experiments:classifyLLMFiles ...")
proc = subprocess.run(
    [gradlew, "experiments:classifyLLMFiles"],
    cwd=str(ROOT),
)
if proc.returncode != 0:
    raise RuntimeError("Gradle classifyLLMFiles task failed (see output above)")

results_csv = GENERATED_DIR / "results.csv"
print(f"\nresults.csv → {results_csv.resolve()}")

Running experiments:classifyLLMFiles ...
> Task :language:generateGrammarSource UP-TO-DATE
> Task :language:compileJava UP-TO-DATE
> Task :util:generateGrammarSource NO-SOURCE
> Task :util:compileJava UP-TO-DATE
> Task :compiler:compileJava UP-TO-DATE
> Task :compiler:processResources UP-TO-DATE
> Task :compiler:classes UP-TO-DATE
> Task :compiler:jar UP-TO-DATE
> Task :experiments:compileJava UP-TO-DATE
> Task :experiments:processResources UP-TO-DATE
> Task :experiments:classes UP-TO-DATE
> Task :language:processResources UP-TO-DATE
> Task :language:classes UP-TO-DATE
> Task :language:jar UP-TO-DATE
> Task :util:processResources NO-SOURCE
> Task :util:classes UP-TO-DATE
> Task :util:jar UP-TO-DATE

> Task :experiments:classifyLLMFiles
Classifying 65 CRML files in: /home/ubuntu/crml/vol/CRML/LLM/generated

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : and og_op : and
Category: null og_op : <= og_op : <=
Category: null og_op : <= og_op : <=
CORRECT       [qwen3.5_27b] SRI_speed1_k1.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Applying operator: ensure (Req_speed1.v<=6.0andReq_speed2.v<=6.0) 'during'fluid_flowing

Category: null og_op : <= og_op : <=
Applying operator: during fluid_flowing

CORRECT       [qwen3.5_27b] SRI_speed1_k2.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Applying operator: ensure Req_speed1.v<=6andReq_speed2.v<=6 'during'true

Category: null og_op : <= og_op : <=
Applying operator: during true

CORRECT       [qwen3.5_27b] SRI_speed1_k3.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Applying operator: ensure temp_ok normal_periods

CORRECT       [qwen3.5_27b] SRI_temp1_k5.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: check anytime temp_normal recovery_window

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

CORRECT       [qwen3.5_27b] SRI_temp2_k1.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
Category: null og_op : <= og_op : <=
Category: null og_op : or og_op : or
Category: null og_op : > og_op : >
Category: null og_op : < og_op : <
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: check anytime normal_temp recovery_window

CORRECT       [qwen3.5_27b] SRI_temp2_k2.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
Category: null og_op : <= og_op : <=
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean in_normal_rangefalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: check at end in_normal_range recovery_period

CORRECT       [qwen3.5_27b] SRI_temp2_k3.crml

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : <= og_op : <=
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean in_normal_rangefalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: check anytime in_normal_range recovery_window

CORRECT       [qwen3.5_27b] SRI_temp2_k4.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : or og_op : or
Category: null og_op : > og_op : >
Category: null og_op : < og_op : <
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
Category: null og_op : <= og_op : <=
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
COMPILATION   [qwen3.5_27b] SRI_temp2_k5.crml
SYNTAX        [qwen3.5_27b] pumpsystem_r1_k1.crml
SYNTAX        [qwen3.5_27b] pumpsystem_r1_k2.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean inOperationfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : or og_op : or
2026-06-09 11:31:35 ERROR crmlVisitorImpl:632 - LOOKUP FAIL: uc.name=[check count] op=['check count'] keys=['check count>', '>=_int', 'evaluateover', 'fromfor', 'or', 'xor', 'until', 'check anytime', 'check count==', '<=_real', '>=_real', 'becomes true', 'before', 'afteruntil', 'cte_true', 'fromwithin', 'countinside', '>_real', 'becomes true inside', 'during', 'decideover', 'from', '<_real', 'frombefore', '>_int', 'set to false', 'when', 'becomes false inside', 'fromuntil', 'check at end', 'ensure', 'check count<', '<_int', '<=_int', 'cte_false', 'afterwithin', 'check count<=', '<>_int', 'inside', 'after', 'check count>=', 'implies', 'checkover', 'afterfor', 'afterbefore', 'becomes false', 'check count<>', 'id', 'set to true', '==_int']
COMPILATION   [qwen3.5_27b] pumpsystem_r1_k3.crml
SYNTAX        [qwen3.5_27b] pumpsystem_r1_k4.crml
SYNTAX        [qwen3.5_27b] pumpsystem_r1_k5.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : or og_op : or
COMPILATION   [qwen3.5_27b] pumpsystem_r2_k1.crml
SYNTAX        [qwen3.5_27b] pumpsystem_r2_k2.crml
SYNTAX        [qwen3.5_27b] pumpsystem_r2_k3.crml
SYNTAX        [qwen3.5_27b] pumpsystem_r2_k4.crml
SYNTAX        [qwen3.5_27b] pumpsystem_r2_k5.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Applying operator: ensure temperature<50 'during'isStarted

Category: null og_op : < og_op : <
Applying operator: during isStarted

CORRECT       [qwen3.5_27b] pumpsystem_r3_k1.crml
SYNTAX        [qwen3.5_27b] pumpsystem_r3_k2.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Applying operator: ensure temperature<50 'during'isStarted

Category: null og_op : < og_op : <
Applying operator: during isStarted

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

CORRECT       [qwen3.5_27b] pumpsystem_r3_k3.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : < og_op : <
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean isStartedfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
VALUES: r1 CRMLtoModelica.Blocks.Integrate
CORRECT       [qwen3.5_27b] pumpsystem_r3_k4.crml
SYNTAX        [qwen3.5_27b] pumpsystem_r3_k5.crml
SYNTAX        [qwen3.5_27b] pumpsystem_r4_k1.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : or og_op : or
Category: null og_op : > og_op : >
Category: null og_op : > og_op : >
Category: null og_op : > og_op : >
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean inOperationfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
COMPILATION   [qwen3.5_27b] pumpsystem_r4_k2.crml
SYNTAX        [qwen3.5_27b] pumpsystem_r4_k3.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean inOperationfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : > og_op : >
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
COMPILATION   [qwen3.5_27b] pumpsystem_r4_k4.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P


Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean night_modefalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Applying operator: check at end yellow green_to_yellow

CORRECT       [qwen3.5_27b] traffic_r2_k1.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean night_modefalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean day_modefalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: check anytime yellow after_green_in_day

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

CORRECT       [qwen3.5_27b] traffic_r2_k2.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean night_modefalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: check anytime true after_green_until_yellow

CORRECT       [qwen3.5_27b] traffic_r2_k3.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean night_modefalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean greenfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: check anytime yellow green_period_during_day

CORRECT       [qwen3.5_27b] traffic_r2_k4.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean night_modefalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: check anytime yellow after_green_in_day

CORRECT       [qwen3.5_27b] traffic_r2_k5.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean night_modefalse

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

CORRECT       [qwen3.5_27b] traffic_r4_k3.crml
SYNTAX        [qwen3.5_27b] traffic_r4_k4.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean night_modefalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
COMPILATION   [qwen3.5_27b] traffic_r4_k5.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean night_modefalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean night_modefalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: ensure (yellowandnotredandnotgreen) night_periods

Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean redfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean greenfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
CORRECT       [qwen3.5_27b] traffic_r5_k1.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean night_modefalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: ensure yellowandnotredandnotgreen 'during'night_mode

Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean redfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean greenfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: during night_mode

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

CORRECT       [qwen3.5_27b] traffic_r5_k2.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean night_modefalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean night_modefalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean redfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean greenfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
COMPILATION   [qwen3.5_27b] traffic_r5_k3.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean night_modefalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean night_modefalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean redfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean greenfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
COMPILATION   [qwen3.5_27b] traffic_r5_k4.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean night_modefalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean night_modefalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean redfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean greenfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
COMPILATION   [qwen3.5_27b] traffic_r5_k5.crml
Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)


Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

results.csv → /home/ubuntu/crml/vol/CRML/LLM/generated/results.csv

## 2  Classification summary

In [2]:
import pandas as pd

cls_df = pd.read_csv(GENERATED_DIR / "results.csv")

# Brief stats
print("=== Classification breakdown ===")
print(cls_df["classification"].value_counts().to_string())
print(f"\nTotal: {len(cls_df)} files")

cls_df.head(10)

=== Classification breakdown ===
classification
CORRECT        25
COMPILATION    25
SYNTAX         15

Total: 65 files

,file,llm,classification,detail
0,/home/ubuntu/crml/vol/CRML/LLM/generated/qwen3...,qwen3.5_27b,CORRECT,NaN
1,/home/ubuntu/crml/vol/CRML/LLM/generated/qwen3...,qwen3.5_27b,CORRECT,NaN
2,/home/ubuntu/crml/vol/CRML/LLM/generated/qwen3...,qwen3.5_27b,CORRECT,NaN
3,/home/ubuntu/crml/vol/CRML/LLM/generated/qwen3...,qwen3.5_27b,CORRECT,NaN
4,/home/ubuntu/crml/vol/CRML/LLM/generated/qwen3...,qwen3.5_27b,COMPILATION,Built in operator undefined : integrate on Boo...
5,/home/ubuntu/crml/vol/CRML/LLM/generated/qwen3...,qwen3.5_27b,COMPILATION,Built in operator undefined : integrate on Boo...
6,/home/ubuntu/crml/vol/CRML/LLM/generated/qwen3...,qwen3.5_27b,CORRECT,NaN
7,/home/ubuntu/crml/vol/CRML/LLM/generated/qwen3...,qwen3.5_27b,CORRECT,NaN
8,/home/ubuntu/crml/vol/CRML/LLM/generated/qwen3...,qwen3.5_27b,CORRECT,NaN
9,/home/ubuntu/crml/vol/CRML/LLM/generated/qwen3...,qwen3.5_27b,CORRECT,NaN

In [3]:
# Per-LLM breakdown
cls_df.groupby(["llm", "classification"]).size().unstack(fill_value=0)

classification  COMPILATION  CORRECT  SYNTAX
llm
qwen3.5_27b              25       25      15

## 3  Build & start JVM for semantic testing

In [4]:
from experiments.gradle_jvm import GradleJvm

jvm = GradleJvm(
    project_path=ROOT,
    subproject="experiments",
    subproject_dir="submodules/experiments",
)
jvm.build()
jvm.start()

Running: /home/ubuntu/crml/vol/CRML/gradlew experiments:shadowJar  (cwd=/home/ubuntu/crml/vol/CRML)
> Task :language:generateGrammarSource UP-TO-DATE
> Task :language:compileJava UP-TO-DATE
> Task :util:generateGrammarSource NO-SOURCE
> Task :util:compileJava UP-TO-DATE
> Task :compiler:compileJava UP-TO-DATE
> Task :compiler:processResources UP-TO-DATE
> Task :compiler:classes UP-TO-DATE
> Task :compiler:jar UP-TO-DATE
> Task :experiments:compileJava UP-TO-DATE
> Task :experiments:processResources UP-TO-DATE
> Task :experiments:classes UP-TO-DATE
> Task :language:processResources UP-TO-DATE
> Task :language:classes UP-TO-DATE
> Task :language:jar UP-TO-DATE
> Task :util:processResources NO-SOURCE
> Task :util:classes UP-TO-DATE
> Task :util:jar UP-TO-DATE
> Task :experiments:shadowJar UP-TO-DATE

BUILD SUCCESSFUL in 1s
12 actionable tasks: 12 up-to-date
Consider enabling configuration cache to speed up this build: https://docs.gradle.org/9.1.0/userguide/configuration_cache_enabling.html
Fat JAR: /home/ubuntu/crml/vol/CRML/submodules/experiments/build/libs/experiments-1.0-SNAPSHOT-all.jar
JVM started.

## 4  Semantic comparison on CORRECT models

For each `CORRECT` model whose domain is registered in `DEFAULT_REGISTRY` (currently `SRI`) **and** that has a `_mapping.json` sidecar, the `FuzzHarness` runs:
- named scenarios from the domain spec
- 20 random fuzz iterations

Models without a mapping, or for domains not yet in the registry, receive `status = no_mapping` / `unknown_domain` without simulation.

**Archive** — each simulation run is saved under `work_dir/<llm>/<domain>_<req>_k<n>/runs/run_NNNN/` containing `result.csv`, `params.json`, and a `run.mos` script that can be opened directly in OpenModelica to re-run the scenario.

In [5]:
from experiments.batch_run import BatchRunner, DEFAULT_REGISTRY
from experiments.harness import CRMLCompiler
from experiments.loader import load_generated

compiler = CRMLCompiler()

# load_generated merges classification from results.csv automatically
df = load_generated(GENERATED_DIR.resolve())

# Run semantic tests only for CORRECT models in supported domains
supported_domains = set(DEFAULT_REGISTRY.keys())
runnable = df[
    (df["classification"] == "CORRECT") &
    (df["domain"].isin(supported_domains))
].copy()

print(f"Supported domains : {supported_domains}")
print(f"CORRECT models    : {(df['classification'] == 'CORRECT').sum()}")
print(f"In registry       : {len(runnable)}")

Supported domains : {'SRI'}
CORRECT models    : 25
In registry       : 12

In [6]:
runner = BatchRunner(
    compiler,
    DEFAULT_REGISTRY,
    n_iters=20,
    seed=42,
    work_dir=Path("~/crml/vol/data").expanduser(),
    keep=True,
    verbose=False,
)

rows = []
for i, (_, row) in enumerate(runnable.iterrows(), 1):
    name = Path(row["crml"]).name
    print(f"[{i:>3}/{len(runnable)}] {name} ...", end=" ", flush=True)
    r = runner.run_row(row)
    print(r["status"])
    rows.append({**r, "crml": row["crml"]})

semantic_df = pd.DataFrame(rows)
print(f"\nDone — {len(semantic_df)} models tested")
print(f"Archives → {runner.work_dir}")

[  1/12] SRI_speed1_k1.crml ... Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: check anytime b P

Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
Category: null og_op : <= og_op : <=
Applying operator: ensure T_in_range ('during'normal_operation)

Applying operator: during normal_operation

Applying operator: check at end T_in_range ('from'(newClock(notR1_T))'for'60.0)

Applying operator: fromfor 60.0 (newClock(notR1_T))

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean R1_Tfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Category: null og_op : > og_op : >
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
Applying operator: ensure f_over_fmin ('during'pump_in_service)

Applying operator: during pump_in_service

Category: null og_op : and og_op : and
Category: null og_op : not og_op : not

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : and og_op : and
Category: null og_op : <= og_op : <=
Category: null og_op : <= og_op : <=
[runner] Setup... /home/ubuntu/crml/vol/data/qwen3.5_27b/SRI_speed1_k1
OMC errors:
  [<interactive>:296:49-296:55:writable] Error: Modified element P not found in class CRMLPeriods_build.
build_error
[  2/12] SRI_speed1_k2.crml ... Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoMode[runner] Setup... /home/ubuntu/crml/vol/data/qwen3.5_27b/SRI_speed1_k2
lica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Applying operator: ensure (Req_speed1.v<=6.0andReq_speed2.v<=6.0) 'during'fluid_flowing

Category: null og_op : <= og_op : <=
Applying operator: during fluid_flowing

OMC errors:
  [<interactive>:296:49-296:55:writable] Error: Modified element P not found in class CRMLPeriods_build.
build_error
[  3/12] SRI_speed1_k3.crml ...

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Applying operator: ensure Req_speed1.v<=6andReq_speed2.v<=6 'during'true

Category: null og_op : <= og_op : <=
Applying operator: during true

[runner] Setup... /home/ubuntu/crml/vol/data/qwen3.5_27b/SRI_speed1_k3
OMC errors:
  [<interactive>:296:49-296:55:writable] Error: Modified element P not found in class CRMLPeriods_build.
build_error
[  4/12] SRI_speed1_k4.crml ... Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : and og_op : and
Category: null og_op : <= og_op : <=
Category: null og_op : <= og_op : <=
[runner] Setup... /home/ubuntu/crml/vol/data/qwen3.5_27b/SRI_speed1_k4
OMC errors:
  [<interactive>:296:49-296:55:writable] Error: Modified element P not found in class CRMLPeriods_build.
build_error
[  5/12] SRI_temp1_k2.crml ...

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og[runner] Setup... /home/ubuntu/crml/vol/data/qwen3.5_27b/SRI_temp1_k2
_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Applying operator: ensure ((T>=16.0)and(T<=30.0)) 'during'normal_operation

Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
Category: null og_op : <= og_op : <=
Applying operator: during normal_operation

OMC errors:
  [<interactive>:296:49-296:55:writable] Error: Modified element P not found in class CRMLPeriods_build.
build_error
[  6/12] SRI_temp1_k3.crml ... Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : <= og_op : <=
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean normal_operationfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: ensure temp_ok P_normal

[runner] Setup... /home/ubuntu/crml/vol/data/qwen3.5_27b/SRI_temp1_k3

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

OMC errors:
  [<interactive>:296:49-296:55:writable] Error: Modified element P not found in class CRMLPeriods_build.
build_error
[  7/12] SRI_temp1_k4.crml ... Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean normal_operationfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: ensure ((T>=16)and(T<=30)) normal_op_periods

Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
Category: null og_op : <= og_op : <=
[runner] Setup... /home/ubuntu/crml/vol/data/qwen3.5_27b/SRI_temp1_k4
OMC errors:
  [<interactive>:296:49-296:55:writable] Error: Modified element P not found in class CRMLPeriods_build.
build_error
[  8/12] SRI_temp1_k5.crml ...

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean normal_operationfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : <= og_op : <=
Applying operator: ensure temp_ok normal_periods

[runner] Setup... /home/ubuntu/crml/vol/data/qwen3.5_27b/SRI_temp1_k5

Added category increasing_real

Added category varying1

Added category varying2

OMC errors:
  [<interactive>:296:49-296:55:writable] Error: Modified element P not found in class CRMLPeriods_build.
build_error
[  9/12] SRI_temp2_k1.crml ... Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: check anytime temp_normal recovery_window

[runner] Setup... /home/ubuntu/crml/vol/data/qwen3.5_27b/SRI_temp2_k1
OMC errors:
  [<interactive>:296:49-296:55:writable] Error: Modified element P not found in class CRMLPeriods_build.
build_error
[ 10/12] SRI_temp2_k2.crml ... Category: null og_op : not og_op : not

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operato[runner] Setup... /home/ubuntu/crml/vol/data/qwen3.5_27b/SRI_temp2_k2
r: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
Category: null og_op : <= og_op : <=
Category: null og_op : or og_op : or
Category: null og_op : > og_op : >
Category: null og_op : < og_op : <
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: check anytime normal_temp recovery_window

OMC errors:
  [<interactive>:296:49-296:55:writable] Error: Modified element P not found in class CRMLPeriods_build.
build_error
[ 11/12] SRI_temp2_k3.crml ... Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
Category: null og_op : <= og_op : <=
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean in_normal_rangefalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: check at end in_normal_range recovery_period

[runner] Setup... /home/ubuntu/crml/vol/data/qwen3.5_27b/SRI_temp2_k3
OMC errors:
  [<interactive>:296:49-296:55:writable] Error: Modified element P not found in class CRMLPeriods_build.
build_error
[ 12/12] SRI_temp2_k4.crml ... Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b2false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(CRMLtoModelica.Functions.not4( b2), CRMLtoModelica.Functions.not4( b1))false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : and og_op : and
Applying operator: or b2 b1

Category: null og_op : not og_op : not
Category: null og_op : and og_op : and
OP DEBUG: not  Boolean CRMLtoModelica.Functions.and4(b2, b1)false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: or b2 notb1

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean b1false
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : filter og_op : filter
Category: null og_op : and og_op : and
Category: null og_op : >= og_op : >=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : start og_op : start
SIG NAME: CRMLtoModelica.Functions.PStart [false]
Category: null og_op : <= og_op : <=
OP DEBUG: tick  Clock Cfalse
SIG NAME: CRMLtoModelica.Blocks.ClockTick [false]
Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
VALUES: r1 CRMLtoModelica.Blocks.EventFilter
Category: null og_op : card og_op : card
Applying operator: inside P C

OP DEBUG: card  Clock 'inside5'.outfalse
SIG NAME: CRMLtoModelica.Blocks.CardClock [false]
Applying operator: becomes true notb

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Applying operator: inside P (b'becomes true')

Applying operator: becomes true b

Applying operator: inside P (b'becomes false')

Applying operator: becomes false b

Applying operator: or newBoolean(Pend) phi

Category: null og_op : end og_op : end
SIG NAME: CRMLtoModelica.Functions.PEnd [false]
OP DEBUG: Boolean  Event CRMLtoModelica.Functions.PEnd(P)false
SIG NAME: CRMLtoModelica.Functions.Event2Boolean [false]
Category: null og_op : * og_op : *
Applying operator: decideover P phi

VALUES: r1 CRMLtoModelica.Blocks.Integrate
Category: null og_op : and og_op : and
FOUND iterator P
OP DEBUG: and  Boolean evaluateover_iteraor1618.outtrue
SIG NAME: CRMLtoModelica.Functions.and4 [false, false]
SIG NAME: CRMLtoModelica.Blocks.setAnd [true]
> : >

>= : >=

< : >=

<= : >

== : >

<> : >

> : >

>= : >=

< : >=

<= : >

Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
Category: null og_op : == og_op : ==
Category: null og_op : <> og_op : <>
Category: null og_op : > og_op : >
Category: null og_op : >= og_op : >=
Category: null og_op : < og_op : <
Category: null og_op : <= og_op : <=
'id' : 'cte_false'

'id' : 'cte_true'

Applying operator: id b

Applying operator: id b

Category: null og_op : not og_op : not
OP DEBUG: not  Boolean bfalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: checkover P ('set to false'b)

Applying operator: set to false b

Applying operator: checkover P ('set to true'b)

Applying operator: set to true b

Applying operator: checkover P (('count'E'inside'P)'<_int'n)

Applying operator: <_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<=_int'n)

Applying operator: <=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>_int'n)

Applying operator: >_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'>=_int'n)

Applying operator: >=_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'==_int'n)

Applying operator: ==_int n ('count'E'inside'P)

Applying operator: countinside P E

Applying operator: checkover P (('count'E'inside'P)'<>_int'n)

Applying operator: <>_int n ('count'E'inside'P)

Applying operator: countinside P E

Category: null og_op : and og_op : and
Applying operator: check count== 0 (b'becomes true') P

Applying operator: becomes true b

Applying operator: check anytime b P

Category: null og_op : <= og_op : <=
Category: null og_op : not og_op : not
OP DEBUG: not  Boolean in_normal_rangefalse
SIG NAME: CRMLtoModelica.Functions.not4 [false]
Category: null og_op : + og_op : +
VALUES: r1 CRMLtoModelica.Blocks.ClockAdd
Applying operator: check anytime in_normal_range recovery_window

[runner] Setup... /home/ubuntu/crml/vol/data/qwen3.5_27b/SRI_temp2_k4

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

Added category increasing_int

Added category increasing_real

Added category varying1

Added category varying2

OMC errors:
  [<interactive>:296:49-296:55:writable] Error: Modified element P not found in class CRMLPeriods_build.
build_error

Done — 12 models tested
Archives → /home/ubuntu/crml/vol/data

## 5  Build extended CSV

Left-join the full classification table with semantic results so every generated file appears in the output, with semantic columns as `NaN` for untested models.

In [7]:
MERGE_KEYS   = ["llm", "domain", "requirement", "attempt"]
SEM_COLS     = ["status", "n_total", "n_failures", "pass_rate",
                "matched_signals", "mismatch_signals", "error"]

# Only keep semantic columns that actually exist in the result
avail_sem = [c for c in SEM_COLS if c in semantic_df.columns]

sem_subset = (
    semantic_df[MERGE_KEYS + avail_sem]
    .rename(columns={"status": "semantic_status", "error": "semantic_error"})
)

extended_df = df.merge(sem_subset, on=MERGE_KEYS, how="left")

out_path = GENERATED_DIR / "results_semantic.csv"
extended_df.to_csv(out_path, index=False)
print(f"Saved {len(extended_df)} rows → {out_path.resolve()}")

Saved 65 rows → /home/ubuntu/crml/vol/CRML/LLM/generated/results_semantic.csv

## 6  Summary

In [8]:
# Semantic results for tested models only
tested = extended_df[extended_df["semantic_status"].notna()].copy()

print("=== Semantic status breakdown ===")
print(tested["semantic_status"].value_counts().to_string())

if "pass_rate" in tested.columns:
    passing = tested[tested["semantic_status"] == "pass"]
    failing = tested[tested["semantic_status"] == "fail"]
    print(f"\nPASS  : {len(passing)}")
    print(f"FAIL  : {len(failing)}")
    if len(failing):
        print("\nFailing models:")
        print(failing[["llm", "domain", "requirement", "attempt",
                        "n_failures", "n_total", "pass_rate",
                        "mismatch_signals"]].to_string(index=False))

=== Semantic status breakdown ===
semantic_status
build_error    12

PASS  : 0
FAIL  : 0

In [9]:
# Per-LLM semantic summary for SRI domain
sri_tested = tested[tested["domain"] == "SRI"].copy()
if len(sri_tested):
    sri_tested["semantically_correct"] = sri_tested["semantic_status"] == "pass"
    print("=== SRI semantic correctness per LLM ===")
    print(
        sri_tested
        .groupby("llm")["semantically_correct"]
        .agg(correct="sum", total="count")
        .assign(rate=lambda x: (x["correct"] / x["total"]).round(3))
        .to_string()
    )

=== SRI semantic correctness per LLM ===
             correct  total  rate
llm
qwen3.5_27b        0     12   0.0

/tmp/ipykernel_361767/4119493389.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sri_tested["semantically_correct"] = sri_tested["semantic_status"] == "pass"
/opt/venv/lib/python3.14/site-packages/pandas/core/frame.py:5246: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data[k] = com.apply_if_callable(v, data)

In [10]:
# Full pipeline funnel: total → correct syntax/compile → semantically correct
total      = len(df)
correct_cl = (df["classification"] == "CORRECT").sum()
in_registry = len(runnable)
sem_pass   = (tested["semantic_status"] == "pass").sum() if len(tested) else 0

print("=== Pipeline funnel ===")
print(f"  Generated          : {total}")
print(f"  CORRECT (compile)  : {correct_cl}  ({100*correct_cl/total:.0f}%)")
print(f"  In harness domain  : {in_registry}")
print(f"  Semantically PASS  : {sem_pass}  ({100*sem_pass/max(in_registry,1):.0f}% of tested)")

=== Pipeline funnel ===
  Generated          : 65
  CORRECT (compile)  : 25  (38%)
  In harness domain  : 12
  Semantically PASS  : 0  (0% of tested)

## Shutdown

In [11]:
jvm.shutdown()

JVM shut down.